apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-fail
spec:
  steps:
    - name: python-fail
      image: python:3.7
      script: |
          #!/usr/bin/env python3
          import sys
          import logging

          FORMAT = '%(asctime)-15s %(message)s'
          logging.basicConfig(format=FORMAT)
          logger = logging.getLogger('server')
          logger.warning('Exit')
          sys.exit(1)
